export const API_URL = "https://5e8ae3466c96.au.ngrok.io/api/v1";

export const TYPES = [
  { name: "TV/Series", slug: "anime-bo" },
  { name: "Mới cập nhật", slug: "anime-moi" },
  { name: "Movie/OVA", slug: "anime-le" },
  { name: "HH Trung Quốc", slug: "hoat-hinh-trung-quoc" },
  { name: "Anime Sắp Chiếu", slug: "anime-sap-chieu" },
];

export const GENRES = [
  { name: "Action", slug: "hanh-dong" },
  { name: "Adventure", slug: "phieu-luu" },
  { name: "Cartoon", slug: "cartoon" },
  { name: "Comedy", slug: "hai-huoc" },
  { name: "Dementia", slug: "dien-loan" },
  { name: "Demons", slug: "demons" },
  { name: "Drama", slug: "drama" },
  { name: "Ecchi", slug: "ecchi" },
  { name: "Fantasy", slug: "phep-thuat" },
  { name: "Game", slug: "tro-choi" },
  { name: "Harem", slug: "harem" },
  { name: "Historical", slug: "lich-su" },
  { name: "Horror", slug: "kinh-di" },
  { name: "Josei", slug: "josei" },
  { name: "Kids", slug: "tre-em" },
  { name: "Live Action", slug: "live-action" },
  { name: "Magic", slug: "ma-thuat" },
  { name: "Martial Arts", slug: "martial-arts" },
  { name: "Mecha", slug: "mecha" },
  { name: "Military", slug: "quan-doi" },
  { name: "Music", slug: "am-nhac" },
  { name: "Mystery", slug: "mystery" },
  { name: "Parody", slug: "parody" },
  { name: "Police", slug: "police" },
  { name: "Psychological", slug: "psychological" },
  { name: "Romance", slug: "tinh-cam" },
  { name: "Samurai", slug: "samurai" },
  { name: "School", slug: "truong-hoc" },
  { name: "Sci-Fi", slug: "sci-fi" },
  { name: "Seinen", slug: "seinen" },
  { name: "Shoujo", slug: "shoujo" },
  { name: "Shoujo Ai", slug: "shoujo-ai" },
  { name: "Shounen", slug: "shounen" },
  { name: "Shounen Ai", slug: "shounen-ai" },
  { name: "Slice of Life", slug: "doi-thuong" },
  { name: "Space", slug: "space" },
  { name: "Sports", slug: "the-thao" },
  { name: "Super Power", slug: "super-power" },
  { name: "Supernatural", slug: "sieu-nhien" },
  { name: "Thriller", slug: "thriller" },
  { name: "Tokusatsu", slug: "tokusatsu" },
  { name: "Vampire", slug: "vampire" },
  { name: "Yaoi", slug: "yaoi" },
  { name: "Yuri", slug: "yuri" },
];

export const SEASONS = [
  {
    name: "Mùa Đông 2021",
    season: "winter",
    year: "2021",
    slug: "winter/2021",
  },
  {
    name: "Mùa Xuân 2021",
    season: "spring",
    year: "2021",
    slug: "spring/2021",
  },
  { name: "Mùa Hạ 2021", season: "summer", year: "2021", slug: "summer/2021" },
  { name: "Mùa Thu 2021", season: "autumn", year: "2021", slug: "autumn/2021" },
  {
    name: "Mùa Đông 2020",
    season: "winter",
    year: "2020",
    slug: "winter/2020",
  },
  {
    name: "Mùa Xuân 2020",
    season: "spring",
    year: "2020",
    slug: "spring/2020",
  },
  { name: "Mùa Hạ 2020", season: "summer", year: "2020", slug: "summer/2020" },
  { name: "Mùa Thu 2020", season: "autumn", year: "2020", slug: "autumn/2020" },
  {
    name: "Mùa Đông 2019",
    season: "winter",
    year: "2019",
    slug: "winter/2019",
  },
  {
    name: "Mùa Xuân 2019",
    season: "spring",
    year: "2019",
    slug: "spring/2019",
  },
  { name: "Mùa Hạ 2019", season: "summer", year: "2019", slug: "summer/2019" },
  { name: "Mùa Thu 2019", season: "autumn", year: "2019", slug: "autumn/2019" },
  {
    name: "Mùa Đông 2018",
    season: "winter",
    year: "2018",
    slug: "winter/2018",
  },
  {
    name: "Mùa Xuân 2018",
    season: "spring",
    year: "2018",
    slug: "spring/2018",
  },
  { name: "Mùa Hạ 2018", season: "summer", year: "2018", slug: "summer/2018" },
  { name: "Mùa Thu 2018", season: "autumn", year: "2018", slug: "autumn/2018" },
  {
    name: "Mùa Đông 2017",
    season: "winter",
    year: "2017",
    slug: "winter/2017",
  },
  {
    name: "Mùa Xuân 2017",
    season: "spring",
    year: "2017",
    slug: "spring/2017",
  },
  { name: "Mùa Hạ 2017", season: "summer", year: "2017", slug: "summer/2017" },
  { name: "Mùa Thu 2017", season: "autumn", year: "2017", slug: "autumn/2017" },
  {
    name: "Mùa Đông 2016",
    season: "winter",
    year: "2016",
    slug: "winter/2016",
  },
  {
    name: "Mùa Xuân 2016",
    season: "spring",
    year: "2016",
    slug: "spring/2016",
  },
  { name: "Mùa Hạ 2016", season: "summer", year: "2016", slug: "summer/2016" },
  { name: "Mùa Thu 2016", season: "autumn", year: "2016", slug: "autumn/2016" },
  {
    name: "Mùa Đông 2015",
    season: "winter",
    year: "2015",
    slug: "winter/2015",
  },
  {
    name: "Mùa Xuân 2015",
    season: "spring",
    year: "2015",
    slug: "spring/2015",
  },
  { name: "Mùa Hạ 2015", season: "summer", year: "2015", slug: "summer/2015" },
  { name: "Mùa Thu 2015", season: "autumn", year: "2015", slug: "autumn/2015" },
  {
    name: "Mùa Đông 2014",
    season: "winter",
    year: "2014",
    slug: "winter/2014",
  },
  {
    name: "Mùa Xuân 2014",
    season: "spring",
    year: "2014",
    slug: "spring/2014",
  },
  { name: "Mùa Hạ 2014", season: "summer", year: "2014", slug: "summer/2014" },
  { name: "Mùa Thu 2014", season: "autumn", year: "2014", slug: "autumn/2014" },
  {
    name: "Mùa Đông 2013",
    season: "winter",
    year: "2013",
    slug: "winter/2013",
  },
  {
    name: "Mùa Xuân 2013",
    season: "spring",
    year: "2013",
    slug: "spring/2013",
  },
  { name: "Mùa Hạ 2013", season: "summer", year: "2013", slug: "summer/2013" },
  { name: "Mùa Thu 2013", season: "autumn", year: "2013", slug: "autumn/2013" },
];

export const SORTS = [
  { name: "Mới nhất", slug: "latest" },
  { name: "Tên: A-Z", slug: "nameaz" },
  { name: "Tên: Z-A", slug: "nameza" },
  { name: "Xem nhiều nhất", slug: "view" },
  { name: "Nhiều lượt bình chọn", slug: "rating" },
];
